apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql:
    use mydb;
    create table product(
    id int AUTO_INCREMENT PRIMARY KEY,
    name varchar(20),
    description varchar(100),
    price decimal(8,3)
    );

    create table coupon(
    id int AUTO_INCREMENT PRIMARY KEY,
    code varchar(20) UNIQUE,
    discount decimal(8,3),
    exp_date varchar(100)
    );

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-app
  labels:
    app: coupon-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coupon-app
  template:
    metadata:
      name: coupon-app
      labels:
        app: coupon-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: coupon-app
          image: jorgelfant/coupon-service
          imagePullPolicy: Always
          ports:
            - containerPort: 9091

---
apiVersion: v1
kind: Service
metadata:
  name: coupon-app
  labels:
    app: coupon-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
      name: http
  selector:
    app: coupon-app

---

apiVersion: v1
kind: Service
metadata:
  name: docker-mysql
  labels:
    app: docker-mysql
spec:
  selector:
    app: docker-mysql
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mysql
  labels:
    app: docker-mysql
spec:
  selector:
    matchLabels:
      app: docker-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: docker-mysql
    spec:
      containers:
        - image: mysql
          name: docker-mysql
          env:
            - name: MYSQL_DATABASE
              value: mydb
            - name: MYSQL_ROOT_PASSWORD
              value: test1234
            - name: MYSQL_ROOT_HOST
              value: '%'
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-initdb-vol
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-initdb-vol
          configMap:
            name: mysql-initdb-config


